[book]
authors = ["Shaikat Majumdar"]
description = "Ultra Low Latency journey with C++."
language = "en"
multilingual = false
src = "."
title = "Ultra Low Latency"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = true

[output.html.playground]
editable = true
line-numbers = true

[output.html.print]
enable = true
page-break = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
